### PR TITLE
Add color to GUI for distinction purposes

### PR DESCRIPTION
**Pull request by endorpersand**
- Adds a red header to the top of the CircuitSim GUI to distinguish it from vanilla CircuitSim
- Adds functionality to support custom color backgrounds (for exam versioning purposes)

### CODE REVIEW

**Comment by Martosis** [comment]
Were any of the color changes ever merged into a released version? If not, does the backwards compatibility check need to be extended?

**Comment by endorpersand** [comment]
The color changes were never merged, but the backcompat check is based on time, so it shouldn't need to be extended. The color field should only be required for files that have been modified after Aug 1, 2024.

**Comment by Martosis** [comment]
> The color changes were never merged, but the backcompat check is based on time, so it shouldn't need to be extended. The color field should only be required for files that have been modified after Aug 1, 2024.

I just realized this said Fall 2024 and not 2023. 🤦
I'll try to have the rest of this reviewed and built hopefully before most people start downloading tomorrow.

**Comment by Martosis** [comment]
holding off on this change since there is no CircuitSim Timed Lab

**Comment by endorpersand** [comment]
Probably won't be used; has too much maintenance cost for not that much benefit

**Pull request closed without merging**
